// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTjPEHedczgP8TRSJp_qmL_OgiQL9_kE',
    appId: '1:712126808260:web:a5b6683a0696787e978991',
    messagingSenderId: '712126808260',
    projectId: 'ujournalcs4750',
    authDomain: 'ujournalcs4750.firebaseapp.com',
    storageBucket: 'ujournalcs4750.firebasestorage.app',
    measurementId: 'G-TVHV7VEL0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZeptpljtUQgZeeHWex-xQiDLoPflySwY',
    appId: '1:712126808260:android:76ad36f5837a4c29978991',
    messagingSenderId: '712126808260',
    projectId: 'ujournalcs4750',
    storageBucket: 'ujournalcs4750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvWv8TuPEZwD_7jtJX0icwgX8HpHcMIeU',
    appId: '1:712126808260:ios:d2a66cc7c667bb50978991',
    messagingSenderId: '712126808260',
    projectId: 'ujournalcs4750',
    storageBucket: 'ujournalcs4750.firebasestorage.app',
    iosBundleId: 'com.jdml.finproCs4750',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvWv8TuPEZwD_7jtJX0icwgX8HpHcMIeU',
    appId: '1:712126808260:ios:d2a66cc7c667bb50978991',
    messagingSenderId: '712126808260',
    projectId: 'ujournalcs4750',
    storageBucket: 'ujournalcs4750.firebasestorage.app',
    iosBundleId: 'com.jdml.finproCs4750',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYTjPEHedczgP8TRSJp_qmL_OgiQL9_kE',
    appId: '1:712126808260:web:60261cbb60ab4a2f978991',
    messagingSenderId: '712126808260',
    projectId: 'ujournalcs4750',
    authDomain: 'ujournalcs4750.firebaseapp.com',
    storageBucket: 'ujournalcs4750.firebasestorage.app',
    measurementId: 'G-TV0TPWGV8F',
  );
}
